quill-lms: Fix missing module import in activity_scores_student_overview
Error reported:

  ERROR in [at-loader] ./app/bundles/admin_dashboard/components/activity_scores_student_overview.tsx:2:29
    TS2307: Cannot find module 'bundles/Teacher/components/progress_reports/student_overview'.